# security-tests/secrets/fake_credentials.py
# DELIBERATELY FAKE DUMMY TEST CREDENTIAL FOR SECRET SCANNING DEMONSTRATION
# (Standard AWS Documentation Non-Functional RFC Example Key)

AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
DB_PASSWORD = "SuperSecretPassword123!#%&"
STRIPE_API_KEY = "sk_test_SAMPLE_MOCK_STRIPE_KEY_REDACTED"
