apiVersion: v1
kind: ServiceAccount
metadata:
  name: sathvik-payment-sa
  namespace: sathvik-workloads
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::009160054307:role/sathvik_payment_workload_role
automountServiceAccountToken: false
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sathvik-payment-hpa
  namespace: sathvik-workloads
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sathvik-payment-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
